version: '3'

services:
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - postgres
    volumes:
      - .:/usr/src/app
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'  